language: python
python:
    - "3.6.5"
addons:
  postgresql: "9.6"

services:
    - postgres

# require travis to first install dependencies
install:
    - pip install -r requirements.txt

before-script:
    - psql -c "DROP DATABASE IF EXISTS stoverflow;" -U postgres
    - psql -c "CREATE DATABASE stoverflowtestdb;" -U postgres
    - python manage.py makemigrations
    - python manage.py migrate

script:
    - coverage run --omit="*tests*,*init*,*migrations*,*wsgi*" --source="apps" manage.py test&&coverage report -m

after_success:
    - coveralls