# Generated by Django 2.2.3 on 2019-07-30 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=203)),
                ('question', models.TextField(verbose_name='Detail')),
                ('question_slug', models.SlugField(blank=True)),
                ('date_asked', models.DateTimeField(auto_now_add=True, verbose_name='Asked On')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_asked'],
            },
        ),
    ]
