# Generated by Django 2.2.3 on 2019-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
